<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue';import{ElMessage,ElMessageBox}from'element-plus';import{createSupplier,deleteSupplier,getSupplier,getSuppliers,updateSupplier}from'../../api/supplier';import type{Supplier}from'../../api/types'
const rows=ref<Supplier[]>([]),total=ref(0),loading=ref(false),visible=ref(false),saving=ref(false),detailVisible=ref(false),detail=ref<Supplier>();const editId=ref<number>();const form=reactive({supplierName:''});const page=reactive({pageNum:0,pageSize:10})
async function load(){loading.value=true;try{const d=await getSuppliers(page);rows.value=d.list||[];total.value=d.total||0}catch(e:any){ElMessage.error(e.message||'加载失败')}finally{loading.value=false}}
function openCreate(){editId.value=undefined;form.supplierName='';visible.value=true}function openEdit(r:Supplier){editId.value=r.id;form.supplierName=r.supplierName;visible.value=true}
async function save(){if(!form.supplierName.trim())return ElMessage.warning('请输入供应商名称');saving.value=true;try{if(editId.value)await updateSupplier(editId.value,{supplierName:form.supplierName.trim()});else await createSupplier({supplierName:form.supplierName.trim()});ElMessage.success('保存成功');visible.value=false;load()}catch(e:any){ElMessage.error(e.message||'保存失败')}finally{saving.value=false}}
async function remove(r:Supplier){try{await ElMessageBox.confirm(`确定删除供应商“${r.supplierName}”？`,'删除确认',{type:'warning'});await deleteSupplier(r.id);ElMessage.success('删除成功');load()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message||'删除失败')}}
async function showDetail(r:Supplier){try{detail.value=await getSupplier(r.id);detailVisible.value=true}catch(e:any){ElMessage.error(e.message||'加载详情失败')}}
onMounted(load)
</script>
<template><div><div class="page-title"><div><h2>供应商管理</h2><p>供应商增删改查</p></div><el-button type="primary" @click="openCreate">新增供应商</el-button></div><el-card shadow="never"><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="supplierName" label="供应商名称" min-width="220"/><el-table-column prop="status" label="状态" width="100"><template #default="{row}"><el-tag :type="row.status===false?'danger':'success'">{{row.status===false?'停用':'正常'}}</el-tag></template></el-table-column><el-table-column prop="createdAt" label="创建时间" width="180"/><el-table-column label="操作" width="220" fixed="right"><template #default="{row}"><el-button link type="primary" @click="showDetail(row)">详情</el-button><el-button link type="warning" @click="openEdit(row)">修改</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination :current-page="page.pageNum+1" :page-size="page.pageSize" :total="total" layout="total,sizes,prev,pager,next" :page-sizes="[10,20,50]" @current-change="(p:number)=>{page.pageNum=p-1;load()}" @size-change="(s:number)=>{page.pageSize=s;page.pageNum=0;load()}"/></div></el-card><el-dialog v-model="visible" :title="editId?'修改供应商':'新增供应商'" width="420px"><el-form label-width="100px"><el-form-item label="供应商名称" required><el-input v-model="form.supplierName"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog><el-dialog v-model="detailVisible" title="供应商详情" width="500px"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item label="ID">{{detail.id}}</el-descriptions-item><el-descriptions-item label="供应商名称">{{detail.supplierName}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.status===false?'停用':'正常'}}</el-descriptions-item><el-descriptions-item label="创建时间">{{detail.createdAt||'-'}}</el-descriptions-item><el-descriptions-item label="更新时间">{{detail.updatedAt||'-'}}</el-descriptions-item></el-descriptions></el-dialog></div></template>
